/*
 * Copyright 2013 Andrew Kroh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.andrewkroh.cisco.xmlservices;

import com.andrewkroh.cisco.phoneinventory.IpPhone;
import com.cisco.xmlservices.generated.CiscoIPPhoneResponse;
import com.google.common.base.Preconditions;

/**
 * Immutable implementation of {@link XmlPushResponse}. This class never
 * returns {@code null}.
 *
 * @author akroh
 */
class DefaultXmlPushResponse implements XmlPushResponse
{
    /**
     * {@code IpPhone} that generated the response.
     */
    private final IpPhone phone;

    /**
     * {@code CiscoIPPhoneResponse} generated by the phone.
     */
    private final CiscoIPPhoneResponse response;

    /**
     * Constructs a new {@code DefaultCiscoXmlPushResponse}.
     *
     * @param phone
     *            {@code IpPhone} that generated the response
     * @param response
     *            {@code CiscoIPPhoneResponse} generated by the phone
     */
    DefaultXmlPushResponse(IpPhone phone, CiscoIPPhoneResponse response)
    {
        this.phone = Preconditions.checkNotNull(phone,
                "IpPhone cannot be null.");
        this.response = Preconditions.checkNotNull(response,
                "CiscoIPPhoneResponse cannot be null.");
    }

    @Override
    public IpPhone getPhone()
    {
        return phone;
    }

    @Override
    public CiscoIPPhoneResponse getResponse()
    {
        return response;
    }
}
